# Generated by Django 6.0.1 on 2026-02-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(default='Geral', max_length=20),
        ),
    ]
